---
language: python
python:
  - "2.7"
  - "3.6"
sudo: required
services:
  - docker
install:
  - pip install docker molecule
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
