---
# file: roles/haproxy/tasks/config.yml
- name: Configuring HAproxy
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: 'haproxy -f %s -c'
  notify: reload haproxy
