---
- import_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: install-Generic.yml
  when: ansible_os_family != 'Debian'

- name: Enabling and starting HAproxy service
  service:
    name: haproxy
    state: started
    enabled: true
