---
- import_tasks: _preliminary_check.yml

- import_tasks: _remove_previous.yml
  when: haproxy_bin.stat.exists

- import_tasks: _create.yml

- import_tasks: _download.yml

- import_tasks: _make.yml

- import_tasks: _install.yml

- import_tasks: _config.yml

- import_tasks: _initd.yml

- import_tasks: _haproxyctl.yml
  when: haproxy_haproxyctl

- name: start haproxy
  service: >
    name=haproxy
    enabled=yes
    state=started
