---
# file: roles/haproxy/tasks/selinux.yml
- name: Allowing HAproxy to listen on some TCP ports
  seport:
    ports: "{{ haproxy_stats_port }}"
    proto: tcp
    setype: tor_port_t
    state: present

- name: Enabling SELinux booleans for HAproxy
  seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true
